version: "3.1"
services:

  registry:
    image: registry:2.6.2
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
